### ISSUE TITLE
Fonction dd

### ISSUE THREAD

**Issue by PaulJulienFrancoBaptista** [cefomk/ceppic_dwwm_foad_09022023#1]
Bonjour c'est Paul, j'ai une question pour la fonction dd, dans l'énoncé c'est écrit une valeur et la détruire. Je ne comprends pas ce que je dois faire pour "détruire".

**Comment by cefomk** [comment]
Bonjour Paul,
en fait cette fonction va nous  servir pour faire du debuggage , 
elle va consister à faire un affichage puis arret l'intrepteur php pour que le reste de la page ne fause notre debug.
Ne t'en fait on verra des exemples demain.

**Comment by PaulJulienFrancoBaptista** [comment]
D'accord merci beaucoup.
